### ISSUE TITLE
Admin Dashboard authentication missing

### ISSUE THREAD

**Issue by HeyIts-RJ** [BigDataIA-Spring2023-Team-07/Assignment-03#11]
## Expected Behavior
Admin dashboard should not be accessed by normal user credentials.

## Current Behavior
I just created a new account also able to view the admin dashboard and all the users available in the platform along with the API calls across the platform.

## Possible Solution
You can put token validation and payload validation check in the backend while sending the response. Also, a check on the front-end to render the UI components depending upon user type i.e. whether it is admin or user. 

## Steps to Reproduce

1. Login into a user account.
2. Click on the hamburger icon and access the sidebar menu.
3. Click on the admin dashboard.

## Video

https://user-images.githubusercontent.com/39235247/226034401-650bacb5-1b7e-479a-bd4e-d2f39113d45c.mov

**Comment by shu3hamiitkgp** [comment]
Thanks for highlighting this, the issue is correct. We'll incorporate limited access to dashboard going forward
