### ISSUE TITLE
Admin Dashboard Navigation Problem

### ISSUE THREAD

**Issue by HeyIts-RJ** [BigDataIA-Spring2023-Team-07/Assignment-03#12]
## Expected Behavior
The dashboard should have the option to navigate to other pages or a button to log out.

## Current Behavior
Admin Dashboard does not have any option to log out or navigate away from the admin dashboard to other pages.

## Possible Solution
Display all the other pages on the sidebar that are accessible by the user as per the permissions. Also, you can have a logout button always visible in your application.

## Steps to Reproduce

1. Login into a user account.
2. Click on the hamburger icon and access the sidebar menu.
3. Click on the admin dashboard.
4. Check the side menu for changes.

## Screenshot
<img width="3008" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/39235247/226040964-7069f1cc-1da8-4346-a200-a65e48df5146.png">

**Comment by shu3hamiitkgp** [comment]
We didn't find it relevant for admin to use the application as such hence didn't provide access to other pages than the dashboard. But I agree the logout button is missing for the dashboard, which we'll incorporate
