### ISSUE TITLE
Logout button is not working

### ISSUE THREAD

**Issue by HeyIts-RJ** [BigDataIA-Spring2023-Team-07/Assignment-03#14]
## Expected Behavior
Logout should clear the session and redirect to the login page.

## Current Behavior
The login button is not functioning.

## Recording

https://user-images.githubusercontent.com/39235247/226051379-995a1fcc-d128-49cf-9baa-12683813b70b.mov

**Comment by shu3hamiitkgp** [comment]
Thanks for highlighting this, I'm able to logout by clicking the button twice. I'm not really sure why it doesn't work in the first go, but will look into it
