### ISSUE TITLE
API limit error message

### ISSUE THREAD

**Issue by krishicago** [BigDataIA-Spring2023-Team-07/Assignment-03#15]
### Expected Behavior:
When the API limit is exceeded there should be an error message mentioning the same for the clarity of the user

### Current Behavior:
When we enter the file names once the API has exceeded the limit, it doesn't show any error message, it does not generate the link, page loads

### Possible Solution:
Display the error message in the code whenever the API limit has exceeded to give more clarity for the end user to understand the issue.

### Steps to Reproduce:
Create a user with new subscription.
Exhaust the user's API calls given.
Retry another API call without renewing the subscription.
Thereafter you can see that the page never submits the new request, it only displays the same data again without showing an error message or some warning.
After this, retry the same API by renewing the subscription.

### Video:
https://user-images.githubusercontent.com/128073685/226057465-4a614902-e3c3-4f57-b2b4-e36c196f6cea.mov

**Comment by shu3hamiitkgp** [comment]
Thanks for highlighting this, the error message comes up for GOES module but is missing for other modules. We'll add the error message
