### ISSUE TITLE
Feedback on documentation

### ISSUE THREAD

**Issue by anushkadesai077** [BigDataIA-Spring2023-Team-07/Assignment-03#7]
Excellent & thorough documentation overall. Just a couple of suggestions/feedbacks:

1. You forgot to add a link to the Airflow instance (if it is live)
2. Updated/new (or same as assignment 2) architectural diagram not provided. Would be better to include it in assignment 3 as well

**Comment by shu3hamiitkgp** [comment]
Thanks for the feedback. Airflow is active, but we didn't add it as it would require credentials to login. We'll provide that separately to you offline. We'll update the architectural diagram
