### ISSUE TITLE
Feedback on code organization

### ISSUE THREAD

**Issue by anushkadesai077** [BigDataIA-Spring2023-Team-07/Assignment-03#8]
Again, you have done a good job with including docstrings and comments everywhere throughout your code. As for the file organization:

1. There is an empty file named “do” which you forgot to remove from the repo
2. There is a file named “database.db” in the parent directory. But there is also a folder named “data” which has other .db files. You could have probably also moved the [database.db](https://github.com/BigDataIA-Spring2023-Team-07/Assignment-03/blob/main/database.db) into this “data” folder - not sure if you did this because it is being used in one of the code files within the parent directory
3. There is an extra docker file named [Dockerfile](https://github.com/BigDataIA-Spring2023-Team-07/Assignment-03/blob/main/Dockerfile) which is probably not being used in the application

**Comment by shu3hamiitkgp** [comment]
Thanks for the feedback, I agree there to the points highlighted. database.db is getting created outside the data directory, which going forward we'll put in the data directory itself
